"""add_company_settings_and_invoice_fields

Revision ID: 164c20afe85b
Revises: 44082aafc3ba
Create Date: 2026-03-24 09:38:22.964534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '164c20afe85b'
down_revision: Union[str, None] = '44082aafc3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
