"""add_company_settings_and_invoice_fields

Revision ID: 402d783ab641
Revises: 4b51b900cac9
Create Date: 2026-03-24 09:37:39.762387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '402d783ab641'
down_revision: Union[str, None] = '4b51b900cac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('name_ar', sa.String(length=300), nullable=True),
    sa.Column('tagline', sa.String(length=300), nullable=True),
    sa.Column('tagline_ar', sa.String(length=300), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('address_ar', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('bank_account_name', sa.String(length=200), nullable=True),
    sa.Column('bank_account_no', sa.String(length=100), nullable=True),
    sa.Column('bank_swift', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('bank_address', sa.Text(), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('stamp_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_settings_id'), 'company_settings', ['id'], unique=False)
    op.add_column('invoice_items', sa.Column('details', sa.Text(), nullable=True))
    op.add_column('invoice_items', sa.Column('details_ar', sa.Text(), nullable=True))
    op.add_column('invoice_items', sa.Column('product_image_path', sa.String(length=500), nullable=True))
    op.add_column('invoice_items', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=14, scale=4),
               existing_nullable=False)
    op.add_column('invoices', sa.Column('origin', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('shipping_term', sa.String(length=30), nullable=True))
    op.add_column('invoices', sa.Column('container_no', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('seal_no', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('bl_number', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('vessel_name', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('voyage_number', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('bank_account_name', sa.String(length=200), nullable=True))
    op.add_column('invoices', sa.Column('bank_account_no', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('bank_swift', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('bank_name', sa.String(length=200), nullable=True))
    op.add_column('invoices', sa.Column('bank_address', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('stamp_image_path', sa.String(length=500), nullable=True))
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('invoices', 'port_of_loading',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('invoices', 'port_of_discharge',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.drop_column('invoices', 'tax')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('tax', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.alter_column('invoices', 'port_of_discharge',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('invoices', 'port_of_loading',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('invoices', 'stamp_image_path')
    op.drop_column('invoices', 'bank_address')
    op.drop_column('invoices', 'bank_name')
    op.drop_column('invoices', 'bank_swift')
    op.drop_column('invoices', 'bank_account_no')
    op.drop_column('invoices', 'bank_account_name')
    op.drop_column('invoices', 'voyage_number')
    op.drop_column('invoices', 'vessel_name')
    op.drop_column('invoices', 'bl_number')
    op.drop_column('invoices', 'seal_no')
    op.drop_column('invoices', 'container_no')
    op.drop_column('invoices', 'shipping_term')
    op.drop_column('invoices', 'origin')
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.Numeric(precision=14, scale=4),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=3),
               existing_nullable=False)
    op.drop_column('invoice_items', 'sort_order')
    op.drop_column('invoice_items', 'product_image_path')
    op.drop_column('invoice_items', 'details_ar')
    op.drop_column('invoice_items', 'details')
    op.drop_index(op.f('ix_company_settings_id'), table_name='company_settings')
    op.drop_table('company_settings')
    # ### end Alembic commands ###
