"""initial_tables

Revision ID: 4b51b900cac9
Revises: 
Create Date: 2026-03-24 00:12:38.988077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b51b900cac9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_table('clearance_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('clearance_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('storage_fee_per_day', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clearance_agents_id'), 'clearance_agents', ['id'], unique=False)
    op.create_index(op.f('ix_clearance_agents_name'), 'clearance_agents', ['name'], unique=False)
    op.create_table('market_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('target_currency', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_rates_id'), 'market_rates', ['id'], unique=False)
    op.create_table('shipping_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('price_20gp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_40ft', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_40hq', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_air_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transit_sea_days', sa.Integer(), nullable=True),
    sa.Column('transit_air_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_agents_id'), 'shipping_agents', ['id'], unique=False)
    op.create_index(op.f('ix_shipping_agents_name'), 'shipping_agents', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('full_name_ar', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'BRANCH_MANAGER', 'STAFF', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('client_code', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('company_name_ar', sa.String(length=200), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_client_code'), 'clients', ['client_code'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_number', sa.String(length=60), nullable=False),
    sa.Column('container_number', sa.String(length=30), nullable=True),
    sa.Column('container_type', sa.Enum('GP20', 'FT40', 'HQ40', 'AIR', name='containertype'), nullable=False),
    sa.Column('status', sa.Enum('BOOKING', 'IN_TRANSIT', 'ARRIVED', 'CLEARED', 'DELIVERED', 'CANCELLED', name='containerstatus'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('shipping_agent_id', sa.Integer(), nullable=True),
    sa.Column('cbm', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cartons', sa.Integer(), nullable=True),
    sa.Column('net_weight', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('gross_weight', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('port_of_loading', sa.String(length=100), nullable=True),
    sa.Column('port_of_discharge', sa.String(length=100), nullable=True),
    sa.Column('etd', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('freight_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('goods_description', sa.Text(), nullable=True),
    sa.Column('goods_description_ar', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipping_agent_id'], ['shipping_agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_containers_booking_number'), 'containers', ['booking_number'], unique=True)
    op.create_index(op.f('ix_containers_id'), 'containers', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_type', sa.Enum('PRICE_OFFER', 'PI', 'CI', 'PL', 'SC', name='invoicetype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'APPROVED', 'PAID', 'CANCELLED', name='invoicestatus'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('port_of_loading', sa.String(length=100), nullable=True),
    sa.Column('port_of_discharge', sa.String(length=100), nullable=True),
    sa.Column('shipping_marks', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('notes_ar', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('hs_code', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cartons', sa.Integer(), nullable=True),
    sa.Column('net_weight', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('gross_weight', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('cbm', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_containers_id'), table_name='containers')
    op.drop_index(op.f('ix_containers_booking_number'), table_name='containers')
    op.drop_table('containers')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_code'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shipping_agents_name'), table_name='shipping_agents')
    op.drop_index(op.f('ix_shipping_agents_id'), table_name='shipping_agents')
    op.drop_table('shipping_agents')
    op.drop_index(op.f('ix_market_rates_id'), table_name='market_rates')
    op.drop_table('market_rates')
    op.drop_index(op.f('ix_clearance_agents_name'), table_name='clearance_agents')
    op.drop_index(op.f('ix_clearance_agents_id'), table_name='clearance_agents')
    op.drop_table('clearance_agents')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_table('branches')
    # ### end Alembic commands ###
